-- noinspection AnnotatorForFile

-- noinspection AnnotatorForFile

-- noinspection AnnotatorForFile

-- noinspection AnnotatorForFile

-- noinspection AnnotatorForFile

-- noinspection AnnotatorForFile

DEFINE TABLE gamelog_locations SCHEMALESS;

DEFINE FIELD created_at ON gamelog_locations;
DEFINE FIELD world_name ON gamelog_locations;
DEFINE FIELD world_instance ON gamelog_locations;
DEFINE FIELD time ON gamelog_locations;
DEFINE FIELD group_name ON gamelog_locations;
